//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baitap
{
    using System;
    using System.Collections.Generic;
    
    public partial class sv
    {
        public string masv { get; set; }
        public string tensv { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string gioitinh { get; set; }
        public string khoa { get; set; }
        public Nullable<double> diem1 { get; set; }
        public Nullable<double> diem2 { get; set; }
        public Nullable<double> diem3 { get; set; }
        public Nullable<double> diem4 { get; set; }
    }
}
